#! /bin/sh
gap=15
PANEL_HEIGHT=25
export gap
export PANEL_HEIGHT


#bspc monitor HDMI-1 -d i ii iii
#bspc monitor eDP-1 -d iv v 


bspwm-workspaces &

bspc config border_width         1
bspc config window_gap           $gap
bspc config top_padding		 $(($PANEL_HEIGHT-$gap))
bspc config left_padding	 -$gap
bspc config right_padding	 -$gap
bspc config bottom_padding	 -$gap

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
#bspc config paddingless_monocle  false

bspc config normal_border_color  '#b6c3c5'
bspc config focused_border_color '#2F9DB5'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zathura state=tiled
bspc rule -a Emacs state=tiled

limepanel &
