#! /bin/sh

bspc monitor eDP-1 -d I II
#bspc monitor HDMI-1 -d III IV V 

bspc config border_width         10
bspc config window_gap           32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#b6c3c5'
bspc config focused_border_color '#2F9DB5'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zathura state=tiled
