alias nausea='nausea ~/etc/audio.fifo'
alias mutt='env TERM=vt220 mutt'
alias dvtm='dvtm-custom'
alias newsesh='abduco -c 1 dvtm-custom'
alias neofetch='neofetch --gtk3 off --gtk2 off'
alias mkdir='mkdir -p'
alias ermac='emacs'
alias pic='sxiv -a'
alias spd='sudo prt-get depinst'
alias sps='sudo prt-get search'
alias spi='sudo prt-get info'
alias ..='cd ..'
alias d2pdf='swriter --convert-to pdf'
alias p2pdf='simpress --convert-to pdf'
alias nb='newsbeuter -C ~/.config/newsbeuter/config'
alias rtv='BROWSER=$BROWSER EDITOR="vis" rtv'
alias xsnow='xsnow -notrees -nosanta -norudolf'

# arch
alias ss='sudo aura -S'
alias sa='sudo aura -A'
alias sr='sudo aura -Runs'
alias si='sudo aura -Ss'

alias c='cd'
alias e='emacs -nw' 
alias s='ssh'
alias x='clear'
alias l='ls'
alias t='tmux'
alias v='vis'
alias rm='rm -r'
