alias nausea='nausea ~/etc/audio.fifo'
alias mutt='env TERM=vt220 mutt'
alias dvtm='dvtm-custom'
alias neofetch='neofetch --gtk3 off --gtk2 off'
alias mkdir='mkdir -p'
alias ermac='emacs'
alias pic='sxiv -ab'
alias spd='sudo prt-get depinst'
alias sps='sudo prt-get search'
alias spi='sudo prt-get info'
alias ..='cd ..'
alias d2pdf='swriter --convert-to pdf'
alias p2pdf='simpress --convert-to pdf'
alias nb='newsbeuter -C ~/.config/newsbeuter/config'
alias rtv='BROWSER=$BROWSER EDITOR=$EDITOR rtv'
alias xsnow='xsnow -notrees -nosanta -norudolf'
#alias startx='csc'
alias suod='sudo' #becausei'mretarded
alias eb="edbrowse"

# arch
alias sa='sudo aura -A'
alias ss='sudo aura -S'
alias sr='sudo aura -Runs'
alias si='sudo aura -As'

alias c='cd'
alias e='emacs -nw' 
alias s='ssh'
alias x='clear'
alias l='ls'
alias t='tmux'
alias v='vi'
alias rm='rm -r'
