(use-package company
  :ensure t)
;(use-package company-ghc
;  :ensure t)
(use-package counsel
  :ensure t)
(use-package ess
  :ensure t)
(use-package geiser
  :ensure t)
(use-package ghc
  :ensure t)
(use-package haskell-mode
  :ensure t)
(use-package magit
  :ensure t)
(use-package swiper
  :ensure t)
(use-package all-the-icons
  :ensure t)
(use-package all-the-icons-dired
  :ensure t)
(use-package base16-theme
  :ensure t)
(use-package cdlatex
  :ensure t)
(use-package circe
  :ensure t)
(use-package emms
  :ensure t)
;(use-package emms-player-mpv
;  :ensure t)
(use-package intero
  :ensure t)
(use-package multi-term
  :ensure t)
(use-package neotree
  :ensure t)
(use-package nix-mode
  :ensure t)
(use-package pretty-mode
  :ensure t)
(use-package seoul256-theme
  :ensure t)
(use-package simple-mpc
  :ensure t)
(use-package slime
  :ensure t)
(use-package slime-company
  :ensure t)
(use-package spacegray-theme
  :ensure t)
(use-package sublime-themes
  :ensure t)
(use-package use-package
  :ensure t)
(use-package xresources-theme
  :ensure t)
(use-package ace-window
  :ensure t)
(use-package auctex
  :ensure t)
(use-package cl-lib
  :ensure t)
(use-package company
  :ensure t)
(use-package csv-mode
  :ensure t)
