alias nausea='nausea ~/etc/audio.fifo'
alias mutt='env TERM=vt220 mutt'
alias dvtm='dvtm-custom'
alias neofetch='neofetch --gtk3 off --gtk2 off'
alias mkdir='mkdir -p'
alias ermac='emacs'
alias pic='sxiv -ab'
alias spd='sudo prt-get depinst'
alias sps='sudo prt-get search'
alias spi='sudo prt-get info'
alias 'up'='cd ..'
alias d2pdf='swriter --convert-to pdf'
alias p2pdf='simpress --convert-to pdf'
alias nb='newsbeuter -C ~/.config/newsbeuter/config'
alias rtv='BROWSER=$BROWSER EDITOR=$EDITOR rtv --enable-media'
alias xsnow='xsnow -notrees -nosanta -norudolf'
alias suod='sudo' #becausei'mretarded
alias nr='sudo nixos-rebuild switch -I nixpkgs=/home/poq/src/nix/nixpkgs'
alias schleep='systemctl suspend'
alias guixd='sudo ~root/.guix-profile/bin/guix-daemon --build-users-group=guixbuild'

alias eb="edbrowse"
alias c='cd'
alias e='emacs -nw' 
alias s='ssh'
alias x='clear'
alias l='ls'
alias t='tmux'
alias v='mg -n'
alias rm='rm -r'
